In [1]:
import pandas as pd
import numpy as np
df_bus = pd.read_csv('clean_bus.csv')
df_streetcar = pd.read_csv('clean_streetcar.csv')
df_sub = pd.read_csv('clean_sub.csv')

In [2]:
allData = [df_bus, df_streetcar, df_sub]

In [3]:
for a in allData:
    print(a.Hour.unique())

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 23  0  1 22]
[ 1  4  6  7  8 11 12 13 16 18 20 21 23  5  9 14 15 17 19  2  0 10 22  3]
[ 1  2  3  8  9 10 12 14 15 16 17 19 20 22 23  0  5  6  7 11 13 18 21  4]


In [4]:
#adding a flag if the hours were in rush hour
for a in allData:
    a['IsRushHour'] = np.where(
    a['Hour'].between(7, 9) | a['Hour'].between(16, 18),
    1, 0
)

In [5]:
#adding a flag if the days were weekend
for a in allData:
    a['IsWeekend'] = np.where(
    a['DayOfWeek']>=5,
    1, 0
)

In [6]:
#adding a flag if it was night hours
for a in allData:
    a['IsNight'] = np.where(
    a['Hour'].between(0, 5),
    1, 0
)

In [9]:
choices = ['Winter', 'Spring', 'Summer', 'Fall']

for a in allData:
    conditions = [
        a['Month'].isin([12, 1, 2]),
        a['Month'].between(3, 5),
        a['Month'].between(6, 8),
        a['Month'].between(9, 11),
    ]
    a['Season'] = np.select(conditions, choices, default='Unknown')

In [12]:
for a in allData:
    display(a.columns)

Index(['Route', 'Day', 'Location', 'Min Delay', 'Min Gap', 'Direction',
       'Vehicle', 'Incident', 'Direction_known', 'Hour', 'Minute', 'Month',
       'Year', 'DayOfWeek', 'Direction_clean', 'IsRushHour', 'IsWeekend',
       'IsNight', 'Season'],
      dtype='str')

Index(['Line', 'Day', 'Location', 'Incident', 'Min Delay', 'Min Gap', 'Bound',
       'Vehicle', 'Direction_known', 'Hour', 'Minute', 'Month', 'Year',
       'DayOfWeek', 'Direction_clean', 'IsRushHour', 'IsWeekend', 'IsNight',
       'Season'],
      dtype='str')

Index(['Day', 'Location', 'Min Delay', 'Min Gap', 'Direction', 'Route',
       'Vehicle', 'Incident', 'Direction_known', 'Hour', 'Minute', 'Month',
       'Year', 'DayOfWeek', 'Direction_clean', 'IsRushHour', 'IsWeekend',
       'IsNight', 'Season'],
      dtype='str')